apiVersion: v1
kind: Service
metadata:
  name: flask-svc
  namespace: flask-blog
spec:
  type: NodePort # Permite acceso desde fuera del clúster
  selector:
    app: flask-blog # ¡IMPORTANTE! Debe coincidir con los labels de tu Deployment
  ports:
    - protocol: TCP
      port: 80      # Puerto en el que el servicio escucha dentro del clúster
      targetPort: 5000 # El puerto que definiste en tu App (Flask/JS)
      nodePort: 30001  # Puerto que abrirá en la IP de Minikube (rango 30000-32767)